force-app/main/default/objects/GRAXEmbedConfiguration__c/GRAXEmbedConfiguration__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>GRAX Configuration Settings</label>
</CustomObject>

force-app/main/default/objects/GRAXEmbedConfiguration__c/fields/GRAXApiUrl__c.field-meta.xml
<CustomField>
    <fullName>GRAXApiUrl__c</fullName>
    <description>GRAX Api URL</description>
    <inlineHelpText>GRAX Api URL</inlineHelpText>
    <label>API Url</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/GRAXEmbedLWCHelper.cls
Global with sharing class GRAXEmbedLWCHelper {
    public GRAXEmbedLWCHelper() {
    }

    @AuraEnabled(cacheable=true)
    public static GRAXLWCPayload loadLWCPaylod(String objectName, String fields, String objectId, Boolean enforceRowSecurity){
        GRAXLWCPayload lwcPayload = new GRAXLWCPayload(objectName, fields, objectId, enforceRowSecurity);
        return lwcPayload;
    }

    public class GRAXLWCPayload {
        @AuraEnabled
        public String apiPath {get;set;}
        public GRAXLWCPayload(String objectName, String fields, String objectId, Boolean enforceRowSecurity) {
            GRAXEmbedConfiguration__c gxs = GRAXEmbedConfiguration__c.getOrgDefaults();
            this.apiPath = gxs.GRAXApiUrl__c;
        }
    }
}